language: ruby
before_install:
  - gem install bundler
  - rvm install 2.2.3
before_script:
  - psql -c 'create database lunch_ordering_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
rvm:
  - 2.2.3
  - 1.9.3
addons:
  postgresql: "9.4.1"
services:
  - postgresql