development:
  adapter: postgresql
  encoding: unicode
  database: lunch_ordering_dev
  username: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: lunch_ordering_test
  username: postgres