development:
  adapter: postgresql
  encoding: unicode
  database: lunch_ordering_dev
  username: pguser
  password: "123123"

test:
  adapter: postgresql
  encoding: unicode
  database: lunch_ordering_test
  username: pguser
  password: "123123"