# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ecd4ffaecb368ef583052c8ef7e3f902b6086317238a3d8201f4c4fef1c3ebc14c77bf8d0cd3882ba4b3716d6bca40498d580128d6a77607dbf08dcb0159827b

test:
  secret_key_base: 7a5377b4775d073c0ddb4d08763a0ea50a0c69273659760b499f81ad306d583abf7c1295b571453193af69f34f6889b2a6529a9a9e9981a7d6ce5c63dcde5dd6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
